#!groovy

node {
  
  parameters {
        string(defaultValue: "Este es el valor Incorrecto", description: 'K', name: 'APP_VERSION')
  }

  step([$class: 'WsCleanup'])

  stage "Checkout Git repo"
    checkout scm

  stage "Checkout additional repos"
    dir("Configuration_management") {
      git "https://github.com/dvlopez9811/aik-infrastructure"
    }

  stage "Run Packer"
  sh "/opt/packer validate -var=\"appVersion=${params.APP_VERSION}\" -var-file=CD/packer/aik-app_vars.json CD/packer/aik-app.json"
  sh "/opt/packer build -machine-readable -var=\"appVersion=${params.APP_VERSION}\" -var-file=CD/packer/aik-app_vars.json CD/packer/aik-app.json | tee CD/packer/packer.log"
}
